- [CLI] Bugfix: `TypeError: entry_points() got an unexpected keyword argument 'group'`   (`apscheduler==3.10.2` introduced a bug preventing it from working on Python 3.9)